# Project configuration
site_name: "Documentation"
site_description: "Mailscript brings the best features of bots and smart contracts for email."
site_author: mailscript.com
site_url: https://docs.mailscript.com/
edit_uri: "edit/main/docs/"

# Repository
repo_name: mailscript/docs
repo_url: https://github.com/mailscript/docs

# Copyright
copyright: "&copy; Mailscript"

# Configuration
theme:
  name: material
  logo: images/logo-white.png
  favicon: images/favicon.png

extra_css:
  - css/styles.css

nav:
  - Home: index.md
  - CLI:
      - Get started: cli/get-started.md
      - Usage & commands:
          - Overview: cli/commands.md
          - Accessories: cli/accessories.md
          - Addresses: cli/addresses.md
          - Daemon: cli/daemon.md
          - Keys: cli/keys.md
          - Sync: cli/sync.md
          - Workflows: cli/workflows.md
          - Login: cli/login.md
          - Send: cli/send.md
          - Usernames: cli/usernames.md
  #- API: api.md
  #- SDK Clients: sdk-clients.md
